### ISSUE TITLE
样式内联后的一个bug

### ISSUE THREAD

**Issue by huntbao** [genify/toolkit2#2]
样式表中的样式如下：

``` css
.todo-list li .toggle:after {
    content: url('data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" width="40" height="40" viewBox="-10 -18 100 135"><circle cx="50" cy="50" r="50" fill="none" stroke="#ededed" stroke-width="3"/></svg>')
}
```

生成后的内联样式有误，如下所示：

``` css
.todo-list li .toggle:after {
    content:url(data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" width="40" height="40" viewBox="-10 -18 100 135"><circle cx="50" cy="50" r="50" fill="none" stroke="#ededed" stroke-width="3"/></svg>);
}
```

url 的值两边缺少引号所致
